name: Post Submission Issue Created

on:
  issues:
    types: [opened, reopened]

jobs:
    postSubmission:
        runs-on: ubuntu-latest
        if: contains(github.event.issue.labels.*.name, 'post submission')
        steps:
            - name: Respond to issue
              uses: actions/github-script@v6
              id: comment
              with:
                script: |
                    return github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'Thanks for submitting a post!\nThe automated review will begin shortly.\n\nYou can watch the status of the review [here](https://github.com/mosadie/berners-love-you/actions/runs/' + context.runId + ').'
                    }).id;

            - name: Issue Forms Body Parser
              id: parse
              uses: zentered/issue-forms-body-parser@v2.1.1
                
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '16.x'
                cache: 'npm'
                cache-dependency-path: './bly-validator/package-lock.json'
            
            - name: Install Dependencies
              run: npm ci
              working-directory: ./bly-validator

            # - name: Create New Branch
            #   run: git checkout -b submission-${{ github.event.issue.number }}
            #   working-directory: ./berners-love-you

            - name: Run Validator
              run: 'npm start --- --json ${{ toJSON(steps.parse.outputs.data) }} --existing ../berners-love-you/src/posts.json --output ./berners-love-you/src/posts.json'
              working-directory: ./bly-validator

            - name: Commit Changes
              uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                new_branch: submission-${{ github.event.issue.number }}
                message: |
                    'Add post from #${{ github.event.issue.number }}
                    

                    Co-authored-by: ${{ github.event.issue.user.name }} <${{ github.event.issue.user.email }}>'

            - name: Create Pull Request
              id: pull-request
              uses: actions/github-script@v6
              with:
                script: |
                    return github.rest.pulls.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: 'Add post from #' + context.issue.number,
                        head: 'submission-' + context.issue.number,
                        base: 'main',
                        body: 'This pull request was automatically generated by GitHub Actions from issue #${{ github.event.issue.number }}.\nPost link: ${{ toJSON(steps.parse.outputs.data).link.text }}\nPlatform: ${{ toJSON(steps.parse.outputs.data).platform.text }}\n\nCloses #' + context.issue.number
                    }).html_url
            
            - name: Update comment
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.updateComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        comment_id: ${{ steps.comment.outputs.result }},
                        body: 'Thanks for submitting a post!\nThe automated part of the review has finished.\n\n[View the pull request](' + ${{ steps.pull-request.outputs.result }} + ')'
                    })