name: Publish to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'berners-love-you/**'

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: './berners-love-you/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./berners-love-you
      
      - name: Build Site
        run: npm run build
        working-directory: ./berners-love-you

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: "berners-love-you/build/"

  test-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: './berners-love-you/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./berners-love-you
      
      - name: Test Site
        run: npm test
        working-directory: ./berners-love-you

  publish-site:
    needs: [test-site, build-site]

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.4
